### PR TITLE
[Update] Docker Integration and Environment Updates

### PR DESCRIPTION
**Pull request by vaddisrinivas**
#### **Summary:**
This PR introduces Docker and Docker Compose support, along with minor adjustments on Flask and env

---

### **Key Changes:**

1. **Docker Integration:**
   - Added a `Dockerfile` for building the API using Python 3.13-slim.
   - Updated `docker-compose.yml` to include a build section for local image creation.
   - Configured the service to run on a custom bridge network (`custom_bridge`).

2. **Environment Variables:**
   - Introduced `APP_HOST`, `APP_PORT`, and `APP_DEBUG` for easier configuration of the Flask app.

3. **Run Instructions updated on README:**
   - Provided updated instructions for running the API via Docker, with both `docker-compose` and `docker run` commands.
 
---

### **Testing:**
- Ensure Docker and Docker Compose are installed.
- Configure the `.env` file with appropriate environment variables.
- Test both Docker run methods to verify the API runs correctly and the `sync-data` happens

### CODE REVIEW

**Comment by CoolCoderSJ** [comment]
Looks good! Just made some changes regarding wording in the README and the network bridge. I don't think a custom network bridge is necessary at the moment.

**Comment by CoolCoderSJ** [comment]
Also another note- I think it might be nice to setup a github actions script to build an image automatically and publish it to ghcr moving forward. That way, the image is verified + always up to date.

**Comment by vaddisrinivas** [comment]
I completely agree with pushing image via GHA to GHCR - I can add that in following commits - and all you need to do is add your GHCR creds to repo secrets.

For me - in my local testing Docker did not have access to requests coming from phone - but if its working for you without bridge - I am good - lmk!

**Comment by CoolCoderSJ** [comment]
I'm able to access it from another device- it's possible this was most likely a problem with DNS on your end

**Pull request merged**
